### ISSUE TITLE
Client x quit with exit code 1 and signal 0

### ISSUE THREAD

**Issue by gaurishhs** [zbirenbaum/copilot.lua#236]
Hi! whenever i start to type Neovim gives me tons of errors saying and my cpu usage goes rapid increasing with neovim consuming 98%

From the lsp logs it is due to the usage of `__dirname` without .cjs extension

![image](https://github.com/zbirenbaum/copilot.lua/assets/78847111/19aec623-2bee-4fa4-96c0-a71f897ca604)

![image](https://github.com/zbirenbaum/copilot.lua/assets/78847111/34641c49-76b3-4084-8781-b7e1b666253a)
![image](https://github.com/zbirenbaum/copilot.lua/assets/78847111/0eb78cc6-e475-4873-8232-d951ac89634f)
![image](https://github.com/zbirenbaum/copilot.lua/assets/78847111/a880309d-5bfa-40e2-915d-5f99a3aa11b3)

**Comment by julienmarie** [comment]
Similar issue
![CleanShot 2023-11-20 at 18 31 46](https://github.com/zbirenbaum/copilot.lua/assets/189369/26714923-ae16-4236-9265-d9a6c6ac633a)

```                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              \n\nSyntaxError: Unexpected token '{'\n    at wrapSafe (internal/modules/cjs/loader.js:1029:16)\n    at Module._compile (internal/modules/cjs/loader.js:1078:27)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)\n    at Module.load (internal/modules/cjs/loader.js:979:32)\n    at Function.Module._load (internal/modules/cjs/loader.js:819:12)\n    at Module.require (internal/modules/cjs/loader.js:1003:19)\n    at require (internal/modules/cjs/helpers.js:107:18)\n    at Object.<anonymous> (/Users/myusername/.local/share/lunarvim/site/pack/lazy/opt/copilot.lua/copilot/index.js:5:1)\n    at Module._compile (internal/modules/cjs/loader.js:1114:14)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)\n"
```

**Comment by gaurishhs** [comment]
Fixed. It was happening because i had a package.json in my `~` dir which had type: module. but copilot.lua should include a `package.json`
